FROM ruby:3.3

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update

ENV EDITOR=vim
RUN apt-get install -y vim graphviz && \
    echo "set -o vi" >> /root/.bashrc

COPY dx/show-help-in-app-container-then-wait.sh /root
